name: Python CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --user root

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update Arch Linux and install Python
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm python python-pip base-devel

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install testing dependencies
      run: |
        pip install pytest flake8 black mypy

    - name: Check code style with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Check formatting with black
      run: |
        black --check .

    - name: Run type checking with mypy
      run: |
        mypy .

    - name: Run tests with pytest
      run: |
        pytest -v
